apiVersion: v1
kind: ConfigMap
metadata:
  name: <app_name>
  namespace: <app_namespace>
  labels:
    app: <app_name>
data:
   APP_ENVIRONMENT: "<app_environment>"
   APP_BUCKET_NAME: "<app_bucket_name>"
   APP_BUCKET_ARN: "<app_bucket_arn>"
