apiVersion: apps/v1
kind: Deployment
metadata:
  name: <app_name>
  namespace: <app_namespace>
  labels:
    app: <app_name>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <app_name>
  template:
    metadata:
      labels:
        app: <app_name>
    spec:
      containers:
      - name: <app_name>
        image: cloudtruth/bridge-terraform-argocd-application
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: <app_name>
        - secretRef:
            name: <app_name>
