apiVersion: v1
kind: Service
metadata:
  name: <app_name>
  namespace: <app_namespace>
  labels:
    app: <app_name>
spec:
  selector:
    app: <app_name>
  ports:
    - protocol: TCP
      port: 9292
      targetPort: 9292
